### ISSUE TITLE
cofiguration/register

### ISSUE THREAD

**Issue by hnscdg** [cyrilschumacher/typescript-angularjs-requirejs#1]
Hi, I hava a question about your file typescirpt-angularjs-requirejs
I want use angularjs typescript requirejs to dynamiclly load the js file. But using your file, I can not load the controller file, if I use the register file, The vs give a wrong hint about angularjs  module $inject. If I write the $controllerProvider.register directly in the app.ts file, It still can not dynamicly inject the controller file, can you tell what is the problem, Thanks!

**Comment by cyrilschumacher** [comment]
Hello, 
Indeed, there are angular errors that occur. I reworked the project and it works.

- Follow the [README.md](https://github.com/cyrilschumacher/typescript-angularjs-requirejs/blob/master/README.md);
- Create a HTML file: `index.html` in directory: `dist` with the content:

```html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" />
		<title>typescript-angularjs-requirejs</title>
	</head>
	<body>
		<div data-ng-view></div>
		<script data-main="javascript/main" src="javascript/vendor/requirejs/require.js"></script>
	</body>
</html>
```
- Create a HTML file: `test.html` in directory: `dist/view/` with content;

```html
<div>
    <h1>CustomController</h1>
    <p>{{double(5)}}</p>
</div>
```

Enjoy ;)
